import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f9faf6',
        'surface-dim': '#dadad7',
        'surface-bright': '#f9faf6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f1',
        'surface-container': '#eeeeeb',
        'surface-container-high': '#e8e8e5',
        'surface-container-highest': '#e2e3e0',
        'on-surface': '#1a1c1a',
        'on-surface-variant': '#414844',
        'inverse-surface': '#2f312f',
        'inverse-on-surface': '#f0f1ee',
        'outline': '#717973',
        'outline-variant': '#c1c8c2',
        'surface-tint': '#3f6653',
        'primary': '#012d1d',
        'on-primary': '#ffffff',
        'primary-container': '#1b4332',
        'on-primary-container': '#86af99',
        'inverse-primary': '#a5d0b9',
        'secondary': '#5b6300',
        'on-secondary': '#ffffff',
        'secondary-container': '#dfec60',
        'on-secondary-container': '#616a00',
        'tertiary': '#401b1b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5a302f',
        'on-tertiary-container': '#d29895',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#c1ecd4',
        'primary-fixed-dim': '#a5d0b9',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#274e3d',
        'secondary-fixed': '#dfec60',
        'secondary-fixed-dim': '#c2cf47',
        'on-secondary-fixed': '#1a1d00',
        'on-secondary-fixed-variant': '#444b00',
        'tertiary-fixed': '#ffdad8',
        'tertiary-fixed-dim': '#f5b7b4',
        'on-tertiary-fixed': '#331111',
        'on-tertiary-fixed-variant': '#673a39',
        'background': '#f9faf6',
        'on-background': '#1a1c1a',
        'surface-variant': '#e2e3e0',
        'amber-accent': '#FFB300',
        'surface-muted': '#F8FAF9',
        'text-on-dark': '#FFFFFF',
        'border-low-contrast': '#E5E7EB',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'stat-number': ['32px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      spacing: {
        'gutter': '24px',
        'section-padding': '80px',
        'card-padding': '32px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'margin-mobile': '16px',
      },
      boxShadow: {
        'card': '0 4px 20px 0 rgba(1, 45, 29, 0.04)',
        'card-hover': '0 8px 30px 0 rgba(1, 45, 29, 0.08)',
      },
    },
  },
  plugins: [],
}
export default config
